### ISSUE TITLE
hpdi > add probabilities?

### ISSUE THREAD

**Issue by hanecakr** [ahb108/rcarbon#48]
Dear rcarbon developers,

Would it be a good idea to include the probabilities for each date interval to the output of hpdi()?

Adding this ugly for-loop after line 623 of calibration.R should do the trick (I think):
https://github.com/ahb108/rcarbon/blob/30035ee3389944788d70da0f59aabd35c26e0a48/R/calibration.R#L623

          # compute summed probability for each interval
          p_interval <- as.integer(length(starts))
          for ( j in 1:length(starts) ){
               p_interval[j] <- sum(grd$PrDens[starts[j]:ends[j]])
               p_interval[j] <- round(p_interval[j] * 100, 1)
          }
          result[[i]] <- cbind(startCalBP = grd$calBP[starts],
                               endCalBP = grd$calBP[ends],
                               p_perc = p_interval)

Probably more efficient code could be written (but not by me :-/).
Thanks for all the time and effort you've invested into the development of rcarbon!

Kind regards,
Kristof.

**Comment by ercrema** [comment]
Hi Kristof,
Many thanks for the suggestion! I just pushed a commit (16991b2768da0164c37ad968cfc66a2f91ebb4d1), pretty much using the code you suggested (though it returns the raw probability mass rather than the rounded percentages). It should be implemented on the next CRAN version 1.4.1, scheduled to be released very soon.
All Best,
Enrico
